version: '3.8'

services:
  app:
    image: arundeep78/wildfires:latest
    # if you make changes to the app/Docker file then you can uncomment the below section and comment above line
    # to update the images
    
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   # args:
    
    # comment out this section in case using existing piapp image
    env_file:
      - ./.env

    # Overrides default command so things don't shut down after the process ends.
    command: python ./__init__.py && streamlit run --server.port 80 main.py

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    user: appuser

    depends_on:
      - db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:14.5 #latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
     
    env_file:
      - ./.env
    ports:
      - 5432:5432
      - 80:80
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data: null